#include "/Engine/Private/Common.ush"  

RWTexture2D<float4> OutputSurface;

[numthreads(32, 32, 1)]
void MainCS(uint3 ThreadId : SV_DispathThreadID)
{
	//Set up some variables we are going to need
	float sizeX, sizeY;
	OutputSurfaces.GetDimensions(sizeX, sizeY);

	float2 iResolution = float2(sizeX, sizeY);
	float2 uv = (ThreadId.xy / iResolution.xy);
	float4 OutColor = float4(0, 0, 0, 0);
	OutColor.g = 1.0f;

	OutputSurface[ThreadId.xy] = OutColor;
}