#include "/Engine/Private/Common.ush"

struct TestStruct
{
    float3 TestPosition;
};

RWStructuredBuffer<TestStruct> TestStructureBuffer;

RWTexture2D<float4> CloudOutputSurface;

[numthreads(32, 32, 1)]
void MainCS(uint3 ThreadId : SV_DispatchThreadID)
{
    half4 Output = half4(1.0f, 0.5f, 1.0f, 1.0f);
    CloudOutputSurface[ThreadId.xy] = Output;
    TestStructureBuffer[0].TestPosition = float3(0.5, 0.5, 0.5);
}